name: Run tests

on: 
  push:
    branches:
      -"main"

jobs:
  test:
    runs-on: ubuntu-latest
    
    srategy:
      matrix:
        python-version: [3.10,3.11]
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: python3 -m unittest tests)test_*